### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by ZachSaucier** [Jam3/ae-to-json#14]
I've installed ae-to-json and the other requirements and don't get any errors when I run `node someFile.js` with this inside it:

```
var aeToJSON = require('ae-to-json/after-effects');
var ae = require('after-effects');
```

However, if I add `ae.execute(aeToJSON)` afterwards, taken from the instructions, then I get this:

```
SyntaxError: unknown: Unexpected token (1:9)
[0m> 1 | [36mfunction[39m [94m[1m([22m[39m[94m[1m)[22m[39m [32m{[39m
    |          ^
  2 | [36mvar[39m window [1m=[22m [32m{[39m[32m}[39m[1m;[22m
  3 | [94m[1m([22m[39m[36mfunction[39m[94m[1m([22m[39mf[94m[1m)[22m[39m[32m{[39m[36mif[39m[94m[1m([22m[39m[36mtypeof[39m exports[1m===[22m[31m"object"[39m[1m&&[22m[36mtypeof[39m module[1m!==[22m[31m"undefined"[39m[94m[1m)[22m[39m[32m{[39mmodule[1m.[22mexports[1m=[22mf[94m[1m([22m[39m[94m[1m)[22m[39m[32m}[39m[36melse[39m [36mif[39m[94m[1m([22m[39m[36mtypeof[39m define[1m===[22m[31m"function"[39m[1m&&[22mdefine[1m.[22mamd[94m[1m)[22m[39m[32m{[39mdefine[94m[1m([22m[39m[33m[[39m[33m][39m[1m,[22mf[94m[1m)[22m[39m[32m}[39m[36melse[39m[32m{[39m[36mvar[39m g[1m;[22m[36mif[39m[94m[1m([22m[39m[36mtypeof[39m window[1m!==[22m[31m"undefined"[39m[94m[1m)[22m[39m[32m{[39mg[1m=[22mwindow[32m}[39m[36melse[39m [36mif[39m[94m[1m([22m[39m[36mtypeof[39m global[1m!==[22m[31m"undefined"[39m[94m[1m)[22m[39m[32m{[39mg[1m=[22mglobal[32m}[39m[36melse[39m [36mif[39m[94m[1m([22m[39m[36mtypeof[39m self[1m!==[22m[31m"undefined"[39m[94m[1m)[22m[39m[32m{[39mg[1m=[22mself[32m}[39m[36melse[39m[32m{[39mg[1m=[22m[36mthis[39m[32m}[39mg[1m.[22maeToJSON [1m=[22m f[94m[1m([22m[39m[94m[1m)[22m[39m[32m}[39m[32m}[39m[94m[1m)[22m[39m[94m[1m([22m[39m[36mfunction[39m[94m[1m([22m[39m[94m[1m)[22m[39m[32m{[39m[36mvar[39m define[1m,[22mmodule[1m,[22mexports[1m;[22m[36mreturn[39m [94m[1m([22m[39m[36mfunction[39m e[94m[1m([22m[39mt[1m,[22mn[1m,[22mr[94m[1m)[22m[39m[32m{[39m[36mfunction[39m s[94m[1m([22m[39mo[1m,[22mu[94m[1m)[22m[39m[32m{[39m[36mif[39m[94m[1m([22m[39m[1m![22mn[33m[[39mo[33m][39m[94m[1m)[22m[39m[32m{[39m[36mif[39m[94m[1m([22m[39m[1m![22mt[33m[[39mo[33m][39m[94m[1m)[22m[39m[32m{[39m[36mvar[39m a[1m=[22m[36mtypeof[39m require[1m==[22m[31m"function"[39m[1m&&[22mrequire[1m;[22m[36mif[39m[94m[1m([22m[39m[1m![22mu[1m&&[22ma[94m[1m)[22m[39m[36mreturn[39m a[94m[1m([22m[39mo[1m,[22m[1m![22m[35m0[39m[94m[1m)[22m[39m[1m;[22m[36mif[39m[94m[1m([22m[39mi[94m[1m)[22m[39m[36mreturn[39m i[94m[1m([22m[39mo[1m,[22m[1m![22m[35m0[39m[94m[1m)[22m[39m[1m;[22m[36mvar[39m f[1m=[22m[36mnew[39m Error[94m[1m([22m[39m[31m"Cannot find module '"[39m[1m+[22mo[1m+[22m[31m"'"[39m[94m[1m)[22m[39m[1m;[22m[36mthrow[39m f[1m.[22mcode[1m=[22m[31m"MODULE_NOT_FOUND"[39m[1m,[22mf[32m}[39m[36mvar[39m l[1m=[22mn[33m[[39mo[33m][39m[1m=[22m[32m{[39mexports[1m:[22m[32m{[39m[32m}[39m[32m}[39m[1m;[22mt[33m[[39mo[33m][39m[33m[[39m[35m0[39m[33m][39m[1m.[22mcall[94m[1m([22m[39ml[1m.[22mexports[1m,[22m[36mfunction[39m[94m[1m([22m[39me[94m[1m)[22m[39m[32m{[39m[36mvar[39m n[1m=[22mt[33m[[39mo[33m][39m[33m[[39m[35m1[39m[33m][39m[33m[[39me[33m][39m[1m;[22m[36mreturn[39m s[94m[1m([22m[39mn[1m?[22mn[1m:[22me[94m[1m)[22m[39m[32m}[39m[1m,[22ml[1m,[22ml[1m.[22mexports[1m,[22me[1m,[22mt[1m,[22mn[1m,[22mr[94m[1m)[22m[39m[32m}[39m[36mreturn[39m n[33m[[39mo[33m][39m[1m.[22mexports[32m}[39m[36mvar[39m i[1m=[22m[36mtypeof[39m require[1m==[22m[31m"function"[39m[1m&&[22mrequire[1m;[22m[36mfor[39m[94m[1m([22m[39m[36mvar[39m o[1m=[22m[35m0[39m[1m;[22mo[1m<[22mr[1m.[22mlength[1m;[22mo[1m++[22m[94m[1m)[22m[39ms[94m[1m([22m[39mr[33m[[39mo[33m][39m[94m[1m)[22m[39m[1m;[22m[36mreturn[39m s[32m}[39m[94m[1m)[22m[39m[94m[1m([22m[39m[32m{[39m[35m1[39m[1m:[22m[33m[[39m[36mfunction[39m[94m[1m([22m[39mrequire[1m,[22mmodule[1m,[22mexports[94m[1m)[22m[39m[32m{[39m
  4 | [31m'use strict'[39m[1m;[22m[0m
    at Parser.pp.raise (C:\Users\ste\Documents\WAR\node_modules\after-effects\node_modules\babel-core\node_modules\babylon\lib\parser\location.js:22:13)
    at Parser.pp.unexpected (C:\Users\ste\Documents\WAR\node_modules\after-effects\node_modules\babel-core\node_modules\babylon\lib\parser\util.js:89:8)
    at Parser.pp.parseFunction (C:\Users\ste\Documents\WAR\node_modules\after-effects\node_modules\babel-core\node_modules\babylon\lib\parser\statement.js:639:10)
    at Parser.pp.parseFunctionStatement (C:\Users\ste\Documents\WAR\node_modules\after-effects\node_modules\babel-core\node_modules\babylon\lib\parser\statement.js:308:15)
    at Parser.pp.parseStatement (C:\Users\ste\Documents\WAR\node_modules\after-effects\node_modules\babel-core\node_modules\babylon\lib\parser\statement.js:97:19)
    at Parser.pp.parseBlockBody (C:\Users\ste\Documents\WAR\node_modules\after-effects\node_modules\babel-core\node_modules\babylon\lib\parser\statement.js:529:21)
    at Parser.pp.parseTopLevel (C:\Users\ste\Documents\WAR\node_modules\after-effects\node_modules\babel-core\node_modules\babylon\lib\parser\statement.js:36:8)
    at Parser.parse (C:\Users\ste\Documents\WAR\node_modules\after-effects\node_modules\babel-core\node_modules\babylon\lib\parser\index.js:129:19)
    at parse (C:\Users\ste\Documents\WAR\node_modules\after-effects\node_modules\babel-core\node_modules\babylon\lib\index.js:47:47)
    at File.parse (C:\Users\ste\Documents\WAR\node_modules\after-effects\node_modules\babel-core\lib\transformation\file\index.js:517:34)
```

It seems that the AE project is not being converted to JS properly and thus interprets it as this mess of symbols. 

How can I fix this issue?

**Comment by mikkoh** [comment]
@ZachSaucier I'm currently at a conference and will try to look into this when I'm back. From the pathing I notice you're on Windows. I have not tested on windows yet. I will have to check if the issue is caused by this.
