### ISSUE TITLE
Hi master:

### ISSUE THREAD

**Issue by Halishen** [Jam3/ae-to-json#15]
when i use this I get this error in cmd:

> ae-to-json@1.1.2 test F:\ThunderDown\ae-to-json-master\ae-to-json-master
> npm run open-ae; npm run test-build-run; npm run clean-root;

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "open-ae;" "npm" "run" "test-build-run
;" "npm" "run" "clean-root;"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9

npm ERR! missing script: open-ae;
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     F:\ThunderDown\ae-to-json-master\ae-to-json-master\npm-debug.log
npm ERR! Test failed.  See above for more details.
Can you  help me ?

**Comment by Halishen** [comment]
My system is  window7

**Comment by Halishen** [comment]
F:\>cd F:\ThunderDown\ae-to-json-master\ae-to-json-master

F:\ThunderDown\ae-to-json-master\ae-to-json-master>npm install

> ae-to-json@1.1.2 prepublish F:\ThunderDown\ae-to-json-master\ae-to-json-master

> npm run compile-ae


> ae-to-json@1.1.2 compile-ae F:\ThunderDown\ae-to-json-master\ae-to-json-master

> npm run transpile; npm run after-effects;

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "transpile;" "npm" "run" "after-effect
s;"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9

npm ERR! missing script: transpile;
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     F:\ThunderDown\ae-to-json-master\ae-to-json-master\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "compile-ae"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! ae-to-json@1.1.2 compile-ae: `npm run transpile; npm run after-effects;
`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ae-to-json@1.1.2 compile-ae script 'npm run transpile; np
m run after-effects;'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ae-to-json package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run transpile; npm run after-effects;
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ae-to-json
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ae-to-json
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\ThunderDown\ae-to-json-master\ae-to-json-master\npm-debug.log

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.1.1
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! ae-to-json@1.1.2 prepublish: `npm run compile-ae`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ae-to-json@1.1.2 prepublish script 'npm run compile-ae'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ae-to-json package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run compile-ae
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ae-to-json
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ae-to-json
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\ThunderDown\ae-to-json-master\ae-to-json-master\npm-debug.log

F:\ThunderDown\ae-to-json-master\ae-to-json-master>

**Comment by Halishen** [comment]
65 verbose unlock done using C:\Users\Administrator\AppData\Roaming\npm-cache\_locks\staging-5026d533421cd6be.lock for F:\ThunderDown\ae-to-json-master\ae-to-json-master\node_modules\.staging
66 silly executeActions Finishing
67 silly rollbackFailedOptional Starting
68 silly rollbackFailedOptional Finishing
69 silly runTopLevelLifecycles Starting
70 silly install runTopLevelLifecycles
71 silly preinstall ae-to-json@1.1.2 F:\ThunderDown\ae-to-json-master\ae-to-json-master\ae-to-json-1f86e02f
72 info lifecycle ae-to-json@1.1.2~preinstall: ae-to-json@1.1.2
73 silly lifecycle ae-to-json@1.1.2~preinstall: no script for preinstall, continuing
74 silly build ae-to-json@1.1.2
75 info linkStuff ae-to-json@1.1.2
76 silly linkStuff ae-to-json@1.1.2 has F:\ThunderDown\ae-to-json-master as its parent node_modules
77 verbose linkBins ae-to-json@1.1.2
78 verbose linkMans ae-to-json@1.1.2
79 silly install ae-to-json@1.1.2 F:\ThunderDown\ae-to-json-master\ae-to-json-master\ae-to-json-1f86e02f
80 info lifecycle ae-to-json@1.1.2~install: ae-to-json@1.1.2
81 silly lifecycle ae-to-json@1.1.2~install: no script for install, continuing
82 silly postinstall ae-to-json@1.1.2 F:\ThunderDown\ae-to-json-master\ae-to-json-master\ae-to-json-1f86e02f
83 info lifecycle ae-to-json@1.1.2~postinstall: ae-to-json@1.1.2
84 silly lifecycle ae-to-json@1.1.2~postinstall: no script for postinstall, continuing
85 silly prepublish ae-to-json@1.1.2 F:\ThunderDown\ae-to-json-master\ae-to-json-master\ae-to-json-1f86e02f
86 info lifecycle ae-to-json@1.1.2~prepublish: ae-to-json@1.1.2
87 verbose lifecycle ae-to-json@1.1.2~prepublish: unsafe-perm in lifecycle true
88 verbose lifecycle ae-to-json@1.1.2~prepublish: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;F:\ThunderDown\ae-to-json-master\ae-to-json-master\node_modules\.bin;C:\Program Files\nodejs;C:\Program Files\Java\jdk1.8.0_05\bin;C:\Program Files\Java\jdk1.8.0_05\jre\bin;C:\Program Files\nodejs\;C:\Program Files\Adobe\Adobe After Effects CC 2017\Support Files;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\Administrator\AppData\Roaming\npm
89 verbose lifecycle ae-to-json@1.1.2~prepublish: CWD: F:\ThunderDown\ae-to-json-master\ae-to-json-master
90 silly lifecycle ae-to-json@1.1.2~prepublish: Args: [ '/d /s /c', 'npm run compile-ae' ]
91 silly lifecycle ae-to-json@1.1.2~prepublish: Returned: code: 1  signal: null
92 info lifecycle ae-to-json@1.1.2~prepublish: Failed to exec prepublish script
93 warn optional Skipping failed optional dependency /chokidar/fsevents:
94 warn notsup Not compatible with your operating system or architecture: fsevents@1.1.1
95 verbose stack Error: ae-to-json@1.1.2 prepublish: `npm run compile-ae`
95 verbose stack Exit status 1
95 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:245:16)
95 verbose stack     at emitTwo (events.js:106:13)
95 verbose stack     at EventEmitter.emit (events.js:191:7)
95 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
95 verbose stack     at emitTwo (events.js:106:13)
95 verbose stack     at ChildProcess.emit (events.js:191:7)
95 verbose stack     at maybeClose (internal/child_process.js:850:16)
95 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
96 verbose pkgid ae-to-json@1.1.2
97 verbose cwd F:\ThunderDown\ae-to-json-master\ae-to-json-master
98 error Windows_NT 6.1.7601
99 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
100 error node v6.2.0
101 error npm  v3.8.9
102 error code ELIFECYCLE
103 error ae-to-json@1.1.2 prepublish: `npm run compile-ae`
103 error Exit status 1
104 error Failed at the ae-to-json@1.1.2 prepublish script 'npm run compile-ae'.
104 error Make sure you have the latest version of node.js and npm installed.
104 error If you do, this is most likely a problem with the ae-to-json package,
104 error not with npm itself.
104 error Tell the author that this fails on your system:
104 error     npm run compile-ae
104 error You can get information on how to open an issue for this project with:
104 error     npm bugs ae-to-json
104 error Or if that isn't available, you can get their info via:
104 error     npm owner ls ae-to-json
104 error There is likely additional logging output above.
105 verbose exit [ 1, true ]

**Comment by mikkoh** [comment]
@Halishen sorry the version of the [after-effects](https://www.npmjs.com/package/after-effects) module that this module uses did not support Windows. If you'd like to create a PR introducing the newest version of [after-effects](https://www.npmjs.com/package/after-effects) I'd love it.

**Comment by Halishen** [comment]
Thank you  very much!Good luck!
